name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ci_cd_practice_github_actions:v1 .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ci_cd_practice_github_actions:v1

  deploy:
    runs-on: self-hosted # Ensure you have a self-hosted runner set up on your device

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/ci_cd_practice_github_actions:v1

      - name: Deploy Docker image
        run: docker run -d --name ci_cd_practice_container ${{ secrets.DOCKER_USERNAME }}/ci_cd_practice_github_actions:v1
